name = "Chess"
uuid = "717200cc-f167-4fd3-b4bf-b5e480529844"
authors = ["Tord Romstad"]
version = "0.7.2"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Hiccup = "9fb69e20-1954-56bb-a84f-559cc56a8ff7"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Crayons = "4.0.4"
DefaultApplication = "1.0.0"
Formatting = "0.4.2"
Hiccup = "0.2.2"
HypertextLiteral = "0.6.0"
JSON = "0.21.0"
SQLite = "1.0.5"
StaticArrays = "0.12.4"
StatsBase = "0.33.1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
